### ISSUE TITLE
README updates post 1/9 meeting

### ISSUE THREAD

**Issue by juliexxia** [givedirectly/Google-Partnership#409]
- [x] mention bash_profile for creds for mac
- [x] distinguish in readme about mandatory vs non-mandatory instructions
- [x] ask someone to add you to the cypress dashboard (optional)
- [x] cypress how to run test instructions
- [x] add example.json .gitignore 
- [x] don't put your secret inside the github repository
- [x] run yarn if you have an issue (will install deps)
- [x] link to git basics
- [x] add advice to use lint.sh instead of clang-format etc/Replace clang-format/eslint with lint.sh.
- [x] add ogr2ogr install/run suggestions
- [x] earth engine whitelist yourself?

**Comment by janakdr** [comment]
Replace clang-format/eslint with lint.sh.

**Comment by juliexxia** [comment]
add ogr2ogr2 install/run suggestions

**Comment by juliexxia** [comment]
earth engine whitelist yourself?
